// Generated by https://quicktype.io

export interface Message {
    _id?:       string;
    message:   string;
    sender:    number;
    chat:      string;
    activated?: boolean;
    createdAt?: string;
    updatedAt?: string;
}
